Function Convert-PSDotNetPSToScap {}
Function Convert-PSDotNetScapToPS {}
Function Convert-PSFireFoxPSToScap {}
Function Convert-PSFireFoxScapToPS {}
Function Convert-PSIISServerPSToScap {}
Function Convert-PSIISServerScapToPS {}
Function Convert-PSIISSitePSToScap {}
Function Convert-PSIISSiteScapToPS {}
Function Convert-PSInternetExplorerPSToScap {}
Function Convert-PSInternetExplorerScapToPS {}
Function Convert-PSExcel2013PSToScap {}
Function Convert-PSExcel2013ScapToPS {}
Function Convert-PSOutlook2013PSToScap {}
Function Convert-PSOutlook2013ScapToPS {}
Function Convert-PSPowerPoint2013PSToScap {}
Function Convert-PSPowerPoint2013ScapToPS {}
Function Convert-PSWord2013PSToScap {}
Function Convert-PSWord2013ScapToPS {}
Function Convert-PSOracleJREPSToScap {}
Function Convert-PSOracleJREScapToPS {}
Function Convert-PSSqlServer2012DatabasePSToScap {}
Function Convert-PSSqlServer2012DatabaseScapToPS {}
Function Convert-PSSqlServer2012InstancePSToScap {}
Function Convert-PSSqlServer2012InstanceScapToPS {}
Function Convert-PSSqlServer2016InstancePSToScap {}
Function Convert-PSSqlServer2016InstanceScapToPS {}
Function Convert-PSWindowsClientPSToScap {}
Function Convert-PSWindowsClientScapToPS {}
Function Convert-PSWindowsDefenderPSToScap {}
Function Convert-PSWindowsDefenderScapToPS {}
Function Convert-PSWindowsDNSServerPSToScap {}
Function Convert-PSWindowsDNSServerScapToPS {}
Function Convert-PSWindowsFirewallPSToScap {}
Function Convert-PSWindowsFirewallScapToPS {}
Function Convert-PSWindowsServerDCPSToScap {}
Function Convert-PSWindowsServerDCScapToPS {}
Function Convert-PSWindowsServerMSPSToScap {}
Function Convert-PSWindowsServerMSScapToPS {}
Function Convert-PSWindowsServer2016PSToScap {}
Function Convert-PSWindowsServer2016ScapToPS {}